src/netbox/dcim/urls.py
from django.conf.urls import url

from extras.views import ObjectChangeLogView, ImageAttachmentEditView
from ipam.views import ServiceCreateView
from secrets.views import secret_add
from . import views
from .models import (
    Cable,
    ConsolePort,
    ConsoleServerPort,
    Device,
    DeviceRole,
    DeviceType,
    FrontPort,
    Interface,
    Manufacturer,
    Platform,
    PowerPort,
    PowerOutlet,
    Rack,
    RackGroup,
    RackReservation,
    RackRole,
    RearPort,
    Region,
    Site,
    VirtualChassis,
)

app_name = "dcim"
urlpatterns = [
    # Regions
    url(r"^regions/$", views.RegionListView.as_view(), name="region_list"),
    url(r"^regions/add/$", views.RegionCreateView.as_view(), name="region_add"),
    url(
        r"^regions/import/$", views.RegionBulkImportView.as_view(), name="region_import"
    ),
    url(
        r"^regions/delete/$",
        views.RegionBulkDeleteView.as_view(),
        name="region_bulk_delete",
    ),
    url(
        r"^regions/(?P<pk>\d+)/edit/$",
        views.RegionEditView.as_view(),
        name="region_edit",
    ),
    url(
        r"^regions/(?P<pk>\d+)/changelog/$",
        ObjectChangeLogView.as_view(),
        name="region_changelog",
        kwargs={"model": Region},
    ),
    # Sites
    url(r"^sites/$", views.SiteListView.as_view(), name="site_list"),
    url(r"^sites/add/$", views.SiteCreateView.as_view(), name="site_add"),
    url(r"^sites/import/$", views.SiteBulkImportView.as_view(), name="site_import"),
    url(r"^sites/edit/$", views.SiteBulkEditView.as_view(), name="site_bulk_edit"),
    url(r"^sites/(?P<slug>[\w-]+)/$", views.SiteView.as_view(), name="site"),
    url(
        r"^sites/(?P<slug>[\w-]+)/edit/$",
        views.SiteEditView.as_view(),
        name="site_edit",
    ),
    url(
        r"^sites/(?P<slug>[\w-]+)/delete/$",
        views.SiteDeleteView.as_view(),
        name="site_delete",
    ),
    url(
        r"^sites/(?P<slug>[\w-]+)/changelog/$",
        ObjectChangeLogView.as_view(),
        name="site_changelog",
        kwargs={"model": Site},
    ),
    url(
        r"^sites/(?P<object_id>\d+)/images/add/$",
        ImageAttachmentEditView.as_view(),
        name="site_add_image",
        kwargs={"model": Site},
    ),
    # Rack groups
    url(r"^rack-groups/$", views.RackGroupListView.as_view(), name="rackgroup_list"),
    url(
        r"^rack-groups/add/$", views.RackGroupCreateView.as_view(), name="rackgroup_add"
    ),
    url(
        r"^rack-groups/import/$",
        views.RackGroupBulkImportView.as_view(),
        name="rackgroup_import",
    ),
    url(
        r"^rack-groups/delete/$",
        views.RackGroupBulkDeleteView.as_view(),
        name="rackgroup_bulk_delete",
    ),
    url(
        r"^rack-groups/(?P<pk>\d+)/edit/$",
        views.RackGroupEditView.as_view(),
        name="rackgroup_edit",
    ),
    url(
        r"^rack-groups/(?P<pk>\d+)/changelog/$",
        ObjectChangeLogView.as_view(),
        name="rackgroup_changelog",
        kwargs={"model": RackGroup},
    ),
    # Rack roles
    url(r"^rack-roles/$", views.RackRoleListView.as_view(), name="rackrole_list"),
    url(r"^rack-roles/add/$", views.RackRoleCreateView.as_view(), name="rackrole_add"),
    url(
        r"^rack-roles/import/$",
        views.RackRoleBulkImportView.as_view(),
        name="rackrole_import",
    ),
    url(
        r"^rack-roles/delete/$",
        views.RackRoleBulkDeleteView.as_view(),
        name="rackrole_bulk_delete",
    ),
    url(
        r"^rack-roles/(?P<pk>\d+)/edit/$",
        views.RackRoleEditView.as_view(),
        name="rackrole_edit",
    ),
    url(
        r"^rack-roles/(?P<pk>\d+)/changelog/$",
        ObjectChangeLogView.as_view(),
        name="rackrole_changelog",
        kwargs={"model": RackRole},
    ),
    # Rack reservations
    url(
        r"^rack-reservations/$",
        views.RackReservationListView.as_view(),
        name="rackreservation_list",
    ),
    url(
        r"^rack-reservations/edit/$",
        views.RackReservationBulkEditView.as_view(),
        name="rackreservation_bulk_edit",
    ),
    url(
        r"^rack-reservations/delete/$",
        views.RackReservationBulkDeleteView.as_view(),
        name="rackreservation_bulk_delete",
    ),
    url(
        r"^rack-reservations/(?P<pk>\d+)/edit/$",
        views.RackReservationEditView.as_view(),
        name="rackreservation_edit",
    ),
    url(
        r"^rack-reservations/(?P<pk>\d+)/delete/$",
        views.RackReservationDeleteView.as_view(),
        name="rackreservation_delete",
    ),
    url(
        r"^rack-reservations/(?P<pk>\d+)/changelog/$",
        ObjectChangeLogView.as_view(),
        name="rackreservation_changelog",
        kwargs={"model": RackReservation},
    ),
    # Racks
    url(r"^racks/$", views.RackListView.as_view(), name="rack_list"),
    url(
        r"^rack-elevations/$",
        views.RackElevationListView.as_view(),
        name="rack_elevation_list",
    ),
    url(r"^racks/add/$", views.RackEditView.as_view(), name="rack_add"),
    url(r"^racks/import/$", views.RackBulkImportView.as_view(), name="rack_import"),
    url(r"^racks/edit/$", views.RackBulkEditView.as_view(), name="rack_bulk_edit"),
    url(
        r"^racks/delete/$", views.RackBulkDeleteView.as_view(), name="rack_bulk_delete"
    ),
    url(r"^racks/(?P<pk>\d+)/$", views.RackView.as_view(), name="rack"),
    url(r"^racks/(?P<pk>\d+)/edit/$", views.RackEditView.as_view(), name="rack_edit"),
    url(
        r"^racks/(?P<pk>\d+)/delete/$",
        views.RackDeleteView.as_view(),
        name="rack_delete",
    ),
    url(
        r"^racks/(?P<pk>\d+)/changelog/$",
        ObjectChangeLogView.as_view(),
        name="rack_changelog",
        kwargs={"model": Rack},
    ),
    url(
        r"^racks/(?P<rack>\d+)/reservations/add/$",
        views.RackReservationCreateView.as_view(),
        name="rack_add_reservation",
    ),
    url(
        r"^racks/(?P<object_id>\d+)/images/add/$",
        ImageAttachmentEditView.as_view(),
        name="rack_add_image",
        kwargs={"model": Rack},
    ),
    # Manufacturers
    url(
        r"^manufacturers/$",
        views.ManufacturerListView.as_view(),
        name="manufacturer_list",
    ),
    url(
        r"^manufacturers/add/$",
        views.ManufacturerCreateView.as_view(),
        name="manufacturer_add",
    ),
    url(
        r"^manufacturers/import/$",
        views.ManufacturerBulkImportView.as_view(),
        name="manufacturer_import",
    ),
    url(
        r"^manufacturers/delete/$",
        views.ManufacturerBulkDeleteView.as_view(),
        name="manufacturer_bulk_delete",
    ),
    url(
        r"^manufacturers/(?P<slug>[\w-]+)/edit/$",
        views.ManufacturerEditView.as_view(),
        name="manufacturer_edit",
    ),
    url(
        r"^manufacturers/(?P<slug>[\w-]+)/changelog/$",
        ObjectChangeLogView.as_view(),
        name="manufacturer_changelog",
        kwargs={"model": Manufacturer},
    ),
    # Device types
    url(r"^device-types/$", views.DeviceTypeListView.as_view(), name="devicetype_list"),
    url(
        r"^device-types/add/$",
        views.DeviceTypeCreateView.as_view(),
        name="devicetype_add",
    ),
    url(
        r"^device-types/import/$",
        views.DeviceTypeBulkImportView.as_view(),
        name="devicetype_import",
    ),
    url(
        r"^device-types/edit/$",
        views.DeviceTypeBulkEditView.as_view(),
        name="devicetype_bulk_edit",
    ),
    url(
        r"^device-types/delete/$",
        views.DeviceTypeBulkDeleteView.as_view(),
        name="devicetype_bulk_delete",
    ),
    url(
        r"^device-types/(?P<pk>\d+)/$",
        views.DeviceTypeView.as_view(),
        name="devicetype",
    ),
    url(
        r"^device-types/(?P<pk>\d+)/edit/$",
        views.DeviceTypeEditView.as_view(),
        name="devicetype_edit",
    ),
    url(
        r"^device-types/(?P<pk>\d+)/delete/$",
        views.DeviceTypeDeleteView.as_view(),
        name="devicetype_delete",
    ),
    url(
        r"^device-types/(?P<pk>\d+)/changelog/$",
        ObjectChangeLogView.as_view(),
        name="devicetype_changelog",
        kwargs={"model": DeviceType},
    ),
    # Console port templates
    url(
        r"^device-types/(?P<pk>\d+)/console-ports/add/$",
        views.ConsolePortTemplateCreateView.as_view(),
        name="devicetype_add_consoleport",
    ),
    url(
        r"^device-types/(?P<pk>\d+)/console-ports/delete/$",
        views.ConsolePortTemplateBulkDeleteView.as_view(),
        name="devicetype_delete_consoleport",
    ),
    # Console server port templates
    url(
        r"^device-types/(?P<pk>\d+)/console-server-ports/add/$",
        views.ConsoleServerPortTemplateCreateView.as_view(),
        name="devicetype_add_consoleserverport",
    ),
    url(
        r"^device-types/(?P<pk>\d+)/console-server-ports/delete/$",
        views.ConsoleServerPortTemplateBulkDeleteView.as_view(),
        name="devicetype_delete_consoleserverport",
    ),
    # Power port templates
    url(
        r"^device-types/(?P<pk>\d+)/power-ports/add/$",
        views.PowerPortTemplateCreateView.as_view(),
        name="devicetype_add_powerport",
    ),
    url(
        r"^device-types/(?P<pk>\d+)/power-ports/delete/$",
        views.PowerPortTemplateBulkDeleteView.as_view(),
        name="devicetype_delete_powerport",
    ),
    # Power outlet templates
    url(
        r"^device-types/(?P<pk>\d+)/power-outlets/add/$",
        views.PowerOutletTemplateCreateView.as_view(),
        name="devicetype_add_poweroutlet",
    ),
    url(
        r"^device-types/(?P<pk>\d+)/power-outlets/delete/$",
        views.PowerOutletTemplateBulkDeleteView.as_view(),
        name="devicetype_delete_poweroutlet",
    ),
    # Interface templates
    url(
        r"^device-types/(?P<pk>\d+)/interfaces/add/$",
        views.InterfaceTemplateCreateView.as_view(),
        name="devicetype_add_interface",
    ),
    url(

src/netbox/extras/urls.py
from django.conf.urls import url

from extras import views

app_name = "extras"
urlpatterns = [
    # Tags
    url(r"^tags/$", views.TagListView.as_view(), name="tag_list"),
    url(r"^tags/delete/$", views.TagBulkDeleteView.as_view(), name="tag_bulk_delete"),
    url(r"^tags/(?P<slug>[\w-]+)/$", views.TagView.as_view(), name="tag"),
    url(r"^tags/(?P<slug>[\w-]+)/edit/$", views.TagEditView.as_view(), name="tag_edit"),
    url(
        r"^tags/(?P<slug>[\w-]+)/delete/$",
        views.TagDeleteView.as_view(),
        name="tag_delete",
    ),
    # Config contexts
    url(
        r"^config-contexts/$",
        views.ConfigContextListView.as_view(),
        name="configcontext_list",
    ),
    url(
        r"^config-contexts/add/$",
        views.ConfigContextCreateView.as_view(),
        name="configcontext_add",
    ),
    url(
        r"^config-contexts/edit/$",
        views.ConfigContextBulkEditView.as_view(),
        name="configcontext_bulk_edit",
    ),
    url(
        r"^config-contexts/delete/$",
        views.ConfigContextBulkDeleteView.as_view(),
        name="configcontext_bulk_delete",
    ),
    url(
        r"^config-contexts/(?P<pk>\d+)/$",
        views.ConfigContextView.as_view(),
        name="configcontext",
    ),
    url(
        r"^config-contexts/(?P<pk>\d+)/edit/$",
        views.ConfigContextEditView.as_view(),
        name="configcontext_edit",
    ),
    url(
        r"^config-contexts/(?P<pk>\d+)/delete/$",
        views.ConfigContextDeleteView.as_view(),
        name="configcontext_delete",
    ),
    # Image attachments
    url(
        r"^image-attachments/(?P<pk>\d+)/edit/$",
        views.ImageAttachmentEditView.as_view(),
        name="imageattachment_edit",
    ),
    url(
        r"^image-attachments/(?P<pk>\d+)/delete/$",
        views.ImageAttachmentDeleteView.as_view(),
        name="imageattachment_delete",
    ),
    # Reports
    url(r"^reports/$", views.ReportListView.as_view(), name="report_list"),
    url(
        r"^reports/(?P<name>[^/]+\.[^/]+)/$", views.ReportView.as_view(), name="report"
    ),
    url(
        r"^reports/(?P<name>[^/]+\.[^/]+)/run/$",
        views.ReportRunView.as_view(),
        name="report_run",
    ),
    # Change logging
    url(
        r"^changelog/$", views.ObjectChangeListView.as_view(), name="objectchange_list"
    ),
    url(
        r"^changelog/(?P<pk>\d+)/$",
        views.ObjectChangeView.as_view(),
        name="objectchange",
    ),
]

src/netbox/netbox/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.static import serve
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from netbox.views import APIRootView, HomeView, SearchView
from users.views import LoginView, LogoutView
from .admin import admin_site

schema_view = get_schema_view(
    openapi.Info(
        title="NetBox API",
        default_version="v2",
        description="API to access NetBox",
        terms_of_service="https://github.com/digitalocean/netbox",
        contact=openapi.Contact(email="netbox@digitalocean.com"),
        license=openapi.License(name="Apache v2 License"),
    ),
    validators=["flex", "ssv"],
    public=True,
)

_patterns = [
    # Base views
    url(r"^$", HomeView.as_view(), name="home"),
    url(r"^search/$", SearchView.as_view(), name="search"),
    # Login/logout
    url(r"^login/$", LoginView.as_view(), name="login"),
    url(r"^logout/$", LogoutView.as_view(), name="logout"),
    # Apps
    url(r"^circuits/", include("circuits.urls")),
    url(r"^dcim/", include("dcim.urls")),
    url(r"^extras/", include("extras.urls")),
    url(r"^ipam/", include("ipam.urls")),
    url(r"^secrets/", include("secrets.urls")),
    url(r"^tenancy/", include("tenancy.urls")),
    url(r"^user/", include("users.urls")),
    url(r"^virtualization/", include("virtualization.urls")),
    # API
    url(r"^api/$", APIRootView.as_view(), name="api-root"),
    url(r"^api/circuits/", include("circuits.api.urls")),
    url(r"^api/dcim/", include("dcim.api.urls")),
    url(r"^api/extras/", include("extras.api.urls")),
    url(r"^api/ipam/", include("ipam.api.urls")),
    url(r"^api/secrets/", include("secrets.api.urls")),
    url(r"^api/tenancy/", include("tenancy.api.urls")),
    url(r"^api/virtualization/", include("virtualization.api.urls")),
    url(r"^api/docs/$", schema_view.with_ui("swagger"), name="api_docs"),
    url(r"^api/redoc/$", schema_view.with_ui("redoc"), name="api_redocs"),
    url(
        r"^api/swagger(?P<format>.json|.yaml)$",
        schema_view.without_ui(),
        name="schema_swagger",
    ),
    # Serving static media in Django to pipe it through LoginRequiredMiddleware
    url(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    # Admin
    url(r"^admin/", admin_site.urls),
]

if settings.WEBHOOKS_ENABLED:
    _patterns += [url(r"^admin/webhook-backend-status/", include("django_rq.urls"))]

if settings.DEBUG:
    import debug_toolbar

    _patterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

# Prepend BASE_PATH
urlpatterns = [url(r"^{}".format(settings.BASE_PATH), include(_patterns))]

handler500 = "utilities.views.server_error"

src/netbox/templates/inc/ajax_loader.html
{% load static %}
<div class="loading text-center">
    <img src="{% static 'img/ajax-loader.gif' %}" />
</div>

src/netbox/templates/inc/created_updated.html
<p>
    <small class="text-muted">Created {{ obj.created }} &middot; Updated <span title="{{ obj.last_updated }}">{{ obj.last_updated|timesince }}</span> ago</small>
</p>

src/netbox/templates/inc/custom_fields_panel.html
{% with custom_fields=obj.get_custom_fields %}
    {% if custom_fields %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Custom Fields</strong>
            </div>
            <table class="table table-hover panel-body attr-table">
                {% for field, value in custom_fields.items %}
                    <tr>
                        <td>{{ field }}</td>
                        <td>
                            {% if field.type == 300 and value == True %}
                                <i class="glyphicon glyphicon-ok text-success" title="True"></i>
                            {% elif field.type == 300 and value == False %}
                                <i class="glyphicon glyphicon-remove text-danger" title="False"></i>
                            {% elif field.type == 500 and value %}
                                <a href="{{ value }}">{{ value|truncatechars:70 }}</a>
                            {% elif field.type == 200 or value %}
                                {{ value }}
                            {% elif field.required %}
                                <span class="text-warning">Not defined</span>
                            {% else %}
                                <span class="text-muted">&mdash;</span>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endif %}
{% endwith %}

src/netbox/templates/inc/image_attachments.html
{% if images %}
    <table class="table table-hover panel-body">
        <tr>
            <th>Name</th>
            <th>Size</th>
            <th>Created</th>
            <th></th>
        </tr>
        {% for attachment in images %}
            <tr{% if not attachment.size %} class="danger"{% endif %}>
                <td>
                    <i class="fa fa-image"></i>
                    <a href="{{ attachment.image.url }}" target="_blank">{{ attachment }}</a>
                </td>
                <td>{{ attachment.size|filesizeformat }}</td>
                <td>{{ attachment.created }}</td>
                <td class="text-right">
                    {% if perms.extras.change_imageattachment %}
                        <a href="{% url 'extras:imageattachment_edit' pk=attachment.pk %}" class="btn btn-warning btn-xs" title="Edit image">
                            <i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>
                        </a>
                    {% endif %}
                    {% if perms.extras.delete_imageattachment %}
                        <a href="{% url 'extras:imageattachment_delete' pk=attachment.pk %}" class="btn btn-danger btn-xs" title="Delete image">
                            <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <div class="panel-body">
        <span class="text-muted">None</span>
    </div>
{% endif %}

src/netbox/templates/inc/modal.html
<div class="modal fade" id="{{ modal_name }}_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="{{ modal_name }}_modal_title">Modal title</h4>
            </div>
            <div class="modal-body"></div>
        </div>
    </div>
</div>

src/netbox/templates/inc/paginator.html
{% load helpers %}

<div class="paginator pull-right text-right">
    {% if paginator.num_pages > 1 %}
        <nav>
            <ul class="pagination pull-right">
                {% if page.has_previous %}
                    <li><a href="{% querystring request page=page.previous_page_number %}"><i class="fa fa-angle-double-left"></i></a></li>
                {% endif %}
                {% for p in page.smart_pages %}
                    {% if p %}
                        <li{% ifequal page.number p %} class="active"{% endifequal %}><a href="{% querystring request page=p %}">{{ p }}</a></li>
                    {% else %}
                        <li class="disabled"><span>&hellip;</span></li>
                    {% endif %}
                {% endfor %}
                {% if page.has_next %}
                    <li><a href="{% querystring request page=page.next_page_number %}"><i class="fa fa-angle-double-right"></i></a></li>
                {% endif %}
            </ul>
        </nav>
        <form method="get">
            {% for k, v in request.GET.items %}
                {% if k != 'per_page' %}
                    <input type="hidden" name="{{ k }}" value="{{ v }}" />
                {% endif %}
            {% endfor %}
            <select name="per_page" id="per_page">
                {% for n in settings.PER_PAGE_DEFAULTS %}
                    <option value="{{ n }}"{% if page.paginator.per_page == n %} selected="selected"{% endif %}>{{ n }}</option>
                {% endfor %}
            </select> per page
        </form>
    {% endif %}
    {% if page %}
        <div class="text-right text-muted">
            Showing {{ page.start_index }}-{{ page.end_index }} of {{ page.paginator.count }}
        </div>
    {% endif %}
</div>

src/netbox/templates/inc/search_panel.html
{% load form_helpers %}

<div class="panel panel-default">
    <div class="panel-heading">
        <span class="fa fa-search" aria-hidden="true"></span>
        <strong>Search</strong>
    </div>
    <div class="panel-body">
        <form action="." method="get" class="form">
                {% for field in filter_form %}
                    <div class="form-group">
                        {% if field.name == "q" %}
                            <div class="input-group">
                                <input type="text" name="q" class="form-control" placeholder="Search" {% if request.GET.q %}value="{{ request.GET.q }}" {% endif %}/>
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-primary">
                                        <span class="fa fa-search" aria-hidden="true"></span>
                                    </button>
                                </span>
                            </div>
                        {% elif field|widget_type == 'checkboxinput' %}
                            <label for="{{ field.id_for_label }}">{{ field }} {{ field.label }}</label>
                        {% else %}
                            {{ field.label_tag }}
                            {{ field }}
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-search" aria-hidden="true"></span> Apply
                    </button>
                    <a href="." class="btn btn-default">
                        <span class="fa fa-remove" aria-hidden="true"></span> Clear
                    </a>
                </div>
        </form>
    </div>
</div>

src/netbox/templates/inc/table.html
{% load django_tables2 %}

<table{% if table.attrs %} {{ table.attrs.as_html }}{% endif %}>
    {% if table.show_header %}
        <thead>
            <tr>
                {% for column in table.columns %}
                    {% if column.orderable %}
                        <th {{ column.attrs.th.as_html }}><a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a></th>
                    {% else %}
                        <th {{ column.attrs.th.as_html }}>{{ column.header }}</th>
                    {% endif %}
                {% endfor %}
            </tr>
        </thead>
    {% endif %}
    <tbody>
        {% for row in table.page.object_list|default:table.rows %}
            <tr {{ row.attrs.as_html }}>
                {% for column, cell in row.items %}
                    <td {{ column.attrs.td.as_html }}>{{ cell }}</td>
                {% endfor %}
            </tr>
        {% empty %}
            {% if table.empty_text %}
                <tr>
                    <td colspan="{{ table.columns|length }}" class="text-center text-muted">&mdash; {{ table.empty_text }} &mdash;</td>
                </tr>
            {% endif %}
        {% endfor %}
    </tbody>
    {% if table.has_footer %}
        <tfoot>
            <tr>
                {% for column in table.columns %}
                    <td>{{ column.footer }}</td>
                {% endfor %}
            </tr>
        </tfoot>
    {% endif %}
</table>

src/netbox/templates/inc/tags_panel.html
{% load helpers %}

<div class="panel panel-default">
    <div class="panel-heading">
        <span class="fa fa-tags" aria-hidden="true"></span>
        <strong>Tags</strong>
    </div>
    <div class="panel-body text-center">
        {% for tag in tags %}
            <a href="{% querystring request tag=tag.slug %}" class="btn btn-sm {% if tag.slug in request.GET.tag %}btn-primary{% else %}btn-link{% endif %}">{{ tag }} <span class="badge">{{ tag.count }}</span></a>
        {% endfor %}
    </div>
</div>